<?php
// backend/api/config.php

/**
 * Application Configuration
 *
 * This file loads environment variables from the `.env` file in the `backend/` directory
 * and defines them as constants for the application to use.
 *
 * DO NOT EDIT THIS FILE.
 * Create a `.env` file in the `backend/` directory (you can copy `.env.example`)
 * and place your credentials there.
 */

// Load the environment variable loader
require_once __DIR__ . '/env_loader.php';

// Define the path to the .env file, which is in the `backend/` directory
$dotenv_path = __DIR__ . '/../.env';

try {
    // Load the environment variables from the .env file
    load_env($dotenv_path);
} catch (Exception $e) {
    // If the .env file is missing or unreadable, the application cannot run.
    // We send a generic error to the client and log the specific issue.
    // The check_config.php endpoint will provide more detailed diagnostics.
    http_response_code(500);
    header('Content-Type: application/json');
    // Use error_log to avoid exposing file paths to the client.
    error_log($e->getMessage());
    echo json_encode([
        'success' => false,
        'message' => 'A critical server configuration error occurred. The application cannot start. Please check the server logs.'
    ]);
    exit();
}

// --- Database Configuration ---
// These are loaded from your .env file.
// The null coalescing operator (??) provides a default value if the env var is not set.
define('DB_HOST', getenv('DB_HOST') ?? 'localhost');
define('DB_NAME', getenv('DB_NAME') ?? '');
define('DB_USER', getenv('DB_USER') ?? '');
define('DB_PASS', getenv('DB_PASS') ?? '');

// --- Telegram Bot Configuration ---
// These are loaded from your .env file.
define('TELEGRAM_BOT_TOKEN', getenv('TELEGRAM_BOT_TOKEN') ?? '');
define('TELEGRAM_CHANNEL_ID', getenv('TELEGRAM_CHANNEL_ID') ?? '');
define('TELEGRAM_SUPER_ADMIN_ID', getenv('TELEGRAM_SUPER_ADMIN_ID') ?? '');

// Note: The closing PHP tag is intentionally omitted from this file.
