# This workflow builds the Android APK using Capacitor

name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build frontend
        run: cd frontend && CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Sync Capacitor web assets to Android
        run: cd frontend && npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android release APK
        run: cd android && ./gradlew assembleRelease

      # TODO: Add signing step here using your keystore and signing credentials

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk

