name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies (frontend)
      run: cd frontend && npm install

    - name: Build React frontend
      run: cd frontend && npm run build

    - name: Sync Capacitor web assets to Android
      run: cd frontend && npx cap sync android

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Signing step would go here if building a signed release APK.
    # This typically involves:
    # 1. Decoding and saving the keystore file from GitHub Secrets.
    # 2. Creating a `gradle.properties` file with signing configuration using GitHub Secrets.
    # Example (using secrets):
    # - name: Set up signing
    #   run: |
    #     echo "$KEYSTORE_FILE" | base64 --decode > android/app/my-release-key.jks
    #     cat >> android/gradle.properties <<EOF
    #     android.signing.storeFile=my-release-key.jks
    #     android.signing.storePassword=$KEYSTORE_PASSWORD
    #     android.signing.keyAlias=$KEY_ALIAS
    #     android.signing.keyPassword=$KEY_PASSWORD
    #     EOF
    #   env:
    #     KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
    #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Build Android release APK (unsigned)
      run: cd android && ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-unsigned-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk