name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up gradlew execute permission after checkout
      run: chmod +x ./frontend/android/gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew (fallback)
      run: chmod +x ./frontend/android/gradlew

    - name: Print working directory
      run: pwd
      working-directory: ./frontend/android

    - name: List files in working directory
      run: ls -al
      working-directory: ./frontend/android

    - name: Build Android project
      run: bash ./gradlew build
      working-directory: ./frontend/android