name: Android CI & Release APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  tag-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

  build-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Sync Capacitor project
        run: npx cap sync android
        working-directory: ./frontend

      - name: Decode Keystore
        id: decode_keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE }}
        run: |
          KEYSTORE_PATH="${{ runner.temp }}/release.jks"
          echo "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE_PATH
          echo "keystore_path=$KEYSTORE_PATH" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./frontend/android

      - name: Build Release APK with Stacktrace
        run: ./gradlew assembleRelease --stacktrace
        working-directory: ./frontend/android
        env:
          KEYSTORE_PATH: ${{ steps.decode_keystore.outputs.keystore_path }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: List Build Output
        run: ls -R frontend/android/app/build/outputs/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: frontend/android/app/build/outputs/apk/release/*.apk
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
