# This workflow builds and signs an Android APK using Capacitor.

name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    # Use runs-on instead of runs on for correct syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Add Android platform
        run: cd frontend && npx cap add android

      - name: Build React frontend
        run: cd frontend && CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Sync Capacitor web assets to Android
        run: cd frontend && npx cap sync android

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Or other distribution like 'adopt'
          java-version: '17'

      - name: Build Android release APK
        run: cd android && ./gradlew assembleRelease

      # Add signing step here. You will need to decode your keystore file from secrets and use apksigner.

      - name: Upload unsigned APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
