name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build --prefix frontend

    - name: Copy web assets to Android
      run: npx cap sync android --skip-bundle --prefix frontend

    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x ./frontend/android/gradlew

    - name: Build Android Release APK
      run: ./frontend/android/gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: frontend/android/app/build/outputs/apk/release/app-release-unsigned.apk