name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Build React frontend (Skip ESLint)
      run: cd frontend && CI=false npm run build # Set CI=false to disable ESLint in react-scripts

    - name: Sync Capacitor web assets to Android
      run: cd frontend && npx cap sync android

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build