name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json # Adjust if you are using yarn or pnpm

    - name: Install dependencies
      run: cd frontend && npm install

    # - name: Add Android platform # Removed as android directory should be in repo
    #   run: cd frontend && npx cap add android

    - name: Build React Frontend
      run: cd frontend && CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build

    - name: Sync Capacitor web assets to Android
      run: cd frontend && npx cap sync android

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Or other distribution like 'adopt'
        java-version: '17'

    - name: Build Android Release APK
      run: cd frontend && ../android/gradlew assembleRelease -p ../android

    # Add signing step here if needed
    # Requires KEYSTORE_FILE, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD secrets

    - name: Upload unsigned APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
