name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Sync Capacitor project
      run: npx cap sync android
      working-directory: ./frontend

    # 将 chmod 步骤移到 sync 之后，并在其前后添加调试步骤
    - name: Print working directory before chmod (debug)
      run: pwd
      working-directory: ./frontend/android

    - name: List files before chmod (debug)
      run: ls -al
      working-directory: ./frontend/android

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./frontend/android

    - name: Print working directory after chmod (debug)
      run: pwd
      working-directory: ./frontend/android

    - name: List files after chmod (debug)
      run: ls -al
      working-directory: ./frontend/android

    - name: Build Android project
      run: bash ./gradlew build --info
      working-directory: ./frontend/android