name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up gradlew execute permission after checkout
      run: chmod +x ./frontend/android/gradlew

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew (fallback)
      run: chmod +x ./frontend/android/gradlew

    - name: Build Android project
      run: bash ./frontend/android/gradlew build
      working-directory: ./frontend/android