# GitHub Actions Workflow for Deploying Backend API
#
# This workflow automates the deployment of the backend API to a remote server.
# It is triggered on pushes to the 'main' branch that involve changes within the 'backend/' directory.
# Crucially, it excludes server-specific configuration files like '.env' and 'config.php' from the synchronization process.

name: Deploy Backend API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Trigger the workflow if any file in the backend directory changes
      - '!.github/workflows/**' # Do not trigger on workflow changes to avoid loops

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Set up SSH
        # IMPORTANT: Ensure that secrets.SERV00_KEY contains the ENTIRE private key
        # including the "-----BEGIN RSA PRIVATE KEY-----" and "-----END RSA PRIVATE KEY-----" lines,
        # and no extra spaces or newlines.
        # If your key has a passphrase, you need to provide it as a separate secret.
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERV00_KEY }}
          # If your SSH key has a passphrase, uncomment the line below and provide the secret.
          # passphrase: ${{ secrets.SERV00_KEY_PASSPHRASE }}

      - name: 3. Add Server to Known Hosts
        # This prevents the 'Host key verification failed' error by adding the server's host key.
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERV00_HOST }} >> ~/.ssh/known_hosts

      - name: 4. Deploy Backend Files using rsync
        # This is the core deployment step.
        # It synchronizes the 'backend/' directory with the target directory on the server.
        # The '--exclude' flags are critical: they prevent '.env', 'config.php', and logs from being overwritten or deleted.
        run: |
          rsync -avz --delete \
            --exclude '.env' \
            --exclude 'config.php' \
            --exclude 'webhook_log.txt' \
            --exclude 'phpinfo.php' \
            --exclude '.htaccess' \
            ./backend/ ${{ secrets.SERV00_USER }}@${{ secrets.SERV00_HOST }}:${{ secrets.SERV00_PATH }}
