# GitHub Actions Workflow for Deploying Backend API
#
# This workflow automates the deployment of the backend API to a remote server.
# It is triggered on pushes to the 'main' branch that involve changes within the 'backend/' directory.
# Crucially, it excludes server-specific configuration files like '.env' and 'config.php' from the synchronization process.

name: Deploy Backend API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Trigger the workflow if any file in the backend directory changes
      - '!.github/workflows/**' # Do not trigger on workflow changes to avoid loops

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Set up SSH
        # This step configures the SSH connection to the server.
        # It uses secrets to securely store credentials.
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${% raw %}{{ secrets.SERV00_KEY }}{% endraw %}
          # IMPORTANT: If your SSH key has a passphrase, add it here:
          # passphrase: ${% raw %}{{ secrets.SSH_KEY_PASSPHRASE }}{% endraw %} 
          # If your key does NOT have a passphrase, leaving this blank or omitting it is usually fine.
          # However, sometimes explicitly setting it to an empty string can help with libcrypto errors.
          passphrase: '' # Explicitly set to empty string if no passphrase

      - name: 3. Add Server to Known Hosts
        # This prevents the 'Host key verification failed' error by adding the server's host key.
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${% raw %}{{ secrets.SERV00_HOST }}{% endraw %} >> ~/.ssh/known_hosts

      - name: 4. Deploy Backend Files using rsync
        # This is the core deployment step.
        # It synchronizes the 'backend/' directory with the target directory on the server.
        # The '--exclude' flags are critical: they prevent '.env', 'config.php', and logs from being overwritten or deleted.
        run: |
          rsync -avz --delete \
            --exclude '.env' \
            --exclude 'config.php' \
            --exclude 'webhook_log.txt' \
            ./backend/ ${% raw %}{{ secrets.SERV00_USER }}{% endraw %}@${% raw %}{{ secrets.SERV00_HOST }}{% endraw %}:${% raw %}{{ secrets.SERV00_PATH }}{% endraw %}
